### ISSUE TITLE
Summer 2021 update - update existing databases & add GRCh38

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-db-downloader#3]
**Scope**

1. Make `snakemake` run through in summer 2021, IOW: fix broken URLs
2. Update existing databases where available
3. Add support for GRCh38, use gnomAD exomes lift-over for now.
4. Add gnomAD chrMT variants in the same way as helixmtdb was added.

**Non-Scope**

- No GRCh38 for ExAC or thousand genomes.
- No extra databases beyond the existing ones.

**To be discussed**

- What if a database is not available for GRCh38 any more?
    - Proposal from @holtgrewe: document here and skip. Mostly this will be gnomAD-SV which is also hard to lift over.

**TODOs**

- [x] GRCh37, acmg, v2.0, exists
- [ ] GRCh37, clinvar, 20200929, exists
    - https://github.com/bihealth/clinvar-tsv TODO: versionize / add date
- [x] GRCh37, dbSNP, b155, exists
- [x] GRCh37, dbVar, latest, exists
    - which version?
- [x] GRCh37, DGV, 2020, exists
- [x] GRCh37, ensembl_genes, r104, exists
- [x] GRCh37, ensembl_regulatory, latest, exists
- [x] GRCh37, ensembltogenesymbol, latest, exists
    - no change
- [x] GRCh37, ensembltorefseq, latest, exists
    - no change
- [x] GRCh37, ExAC_constraints, r0.3.1, exists
    - no change
    - no GRCh38
- [x] GRCh37, ExAC, r1, exists
    - no change
    - no GRCh38
- [ ] GRCh37, extra-annos, 20200704, exists
    - TODO: link dead
- [ ] GRCh37, gnomAD_constraints, v2.1.1, exists
    - not for GRCh38 / gnomAD r3
- [x] GRCh37, gnomAD_exomes, r2.1.1, exists
- [x] GRCh37, gnomAD_genomes, r2.1.1, exists
- [x] GRCh37, gnomAD_SV, v2.1, exists
    - not for GRCh38
- [x] GRCh37, HelixMTdb, 20200327 exists
- [x] GRCh37, hgmd_public, ensembl_r104, exists
- [x] GRCh37, hgnc, latest, exists
    - any update?
    - TODO: also from genes
    - same for GRCh38 probably
- [ ] GRCh37, hpo, latest, exists
    - broken link
- [x] GRCh37, kegg, april2011, exists
    - no update
- [x] GRCh37, knowngeneaa, latest, exists
    - no update
- [x] GRCh37, mgi, latest, exists
    - no update
    - same for GRCh38
- [x] GRCh37, mim2gene, latest, exists
    - no update
- [x] GRCh37, MITOMAP, 20200116, exists
    - no update
    - same for GRCh38
- [x] GRCh37, mtDB, latest, exists
    - no update
    - same for GRCh38
- [x] GRCh37, ncbi_gene, latest, exists
    - no update
    - same for GRCh38
- [x] GRCh37, refseq_genes, r105, exists
- [x] GRCh37, refseqtoensembl, latest, exists
- [x] GRCh37, refseqtogenesymbol, latest, exists
- [ ] GRCh37, tads_hesc, dixon2012, exists
    - skipped
- [ ] GRCh37, tads_imr90, dixon2012, exists
    - skipped
- [x] GRCh37, thousand_genomes, phase3, exists
    - no change
    - no GRCh38
- [x] GRCh37, vista, latest, exists
    - no change
    - no GRCh38
- [x] GRCh38, clinvar, 20200929, exists
- [x] GRCh38, dbVar, latest, exists
    - which version?
- [x] GRCh38, DGV, 2020, exists
- [x] GRCh38, gnomAD_exomes, r2.1.1, NEW (LIFTOVER)
- [x] GRCh38, gnomAD_genomes, r3, NEW
- [x] GRCh38, dbSNP, b155, exists
    - which version?
- [x] GRCh38, ensembl_genes, r104, exists
- [x] GRCh38, ensembl_regulatory, latest, exists
- [ ] GRCh38, extra-annos, 20200704
    - TODO: link dead
- [x] GRCh38, HelixMTdb, 20200327 exists
- [x] GRCh38, hgmd_public, ensembl_r104, new
- [x] GRCh38, refseq_genes, r39, exists

**Comment by flokraft85** [comment]
- GRCh37, gnomAD_constraints, v2.1.1, exists: if only the pLI, o/e and so on are used in varfish and not the chromosomal positions of the genes, it should be no problem to use the GRCh37 version. Otherweise we can try a liftover.
- genes.snake/hgnc.snake -> for the latest GRCh38 release (GRCh38.p13) only gff files insteadt of the gff3 files were available. However the extracted columns (1,4,5,15 or GeneID, HGNC) have the same content.

- [ ] create a "input file" containing all download links  (please finde attached a file with all links used in the snake files)
[pfade.txt](https://github.com/bihealth/varfish-db-downloader/files/6829125/pfade.txt)
